services:
  "backend-template-service":
    image: "postgres"
    container_name: "backend-template-postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "backend-template"
    ports:
      - "5432:5432"
    volumes:
      - backend-template-postgres-data:/data
    restart: always

volumes:
  backend-template-postgres-data:
